<?php

return [
    'title' => 'SkinSystem',
    'description' => 'Connect Azuriom skin uploads to one authoritative SkinsRestorer server.',
    'updated' => 'SkinSystem synchronization settings were saved.',
    'stats' => [
        'total' => 'Active website skins',
        'submitted' => 'Latest operation submitted',
        'attention' => 'Need attention',
    ],
    'settings' => [
        'title' => 'Synchronization settings',
        'enabled' => 'Enable automatic synchronization',
        'enabled_help' => 'Submit a SkinsRestorer command after each changed upload and clear every recorded destination when removing a skin.',
        'server' => 'Authoritative Minecraft server',
        'select_server' => 'Select an executable server',
        'server_help' => 'Only Minecraft AzLink and RCON servers that can execute console commands are available.',
        'no_servers' => 'No compatible executable Minecraft server is available. Configure AzLink or RCON in Azuriom first.',
        'endpoint' => 'Public PNG endpoint pattern',
        'endpoint_help' => 'SkinsRestorer and MineSkin must be able to retrieve revisioned PNG URLs from this endpoint.',
    ],
    'server_types' => [
        'mc-azlink' => 'AzLink',
        'mc-rcon' => 'RCON',
    ],
    'requirements' => [
        'title' => 'Before enabling synchronization',
        'skinsrestorer' => 'Install and configure SkinsRestorer on the server that owns player skin data.',
        'bridge' => 'Connect that server to Azuriom through AzLink or RCON and select it above.',
        'public_url' => 'Serve Azuriom over a publicly reachable HTTPS URL; localhost and private addresses cannot be fetched by MineSkin.',
        'uuid' => 'Ensure every account has the exact Minecraft UUID used by the server. Offline-mode UUIDs generated by Azuriom are supported.',
        'url_allowlist' => 'If SkinsRestorer enables commands.restrictSkinUrls, add the public Azuriom origin to commands.restrictSkinUrls.list.',
        'skin_api' => 'If Skin API remains installed, disable AzLink\'s legacy skinrestorer-integration option so its join listener does not overwrite SkinSystem.',
        'proxy' => 'For BungeeCord or Velocity proxy mode, select the proxy-side AzLink/server where SkinsRestorer owns its player storage; a backend console is not authoritative.',
        'cache_lock' => 'On multi-node Azuriom installations, use a shared cache store such as Redis or database so per-user synchronization locks work across every node.',
        'scheduler' => 'Run Azuriom\'s scheduler so superseded revision files are cleaned after the 30-day safety window.',
        'https_warning' => 'The configured site URL is not HTTPS. Skin uploads will be saved, but SkinSystem will refuse to submit an insecure URL to SkinsRestorer.',
        'submitted_semantics' => '“Submitted” means Azuriom handed one or more commands to RCON or queued them for AzLink. It does not prove execution; retained clear operations can be submitted again safely.',
    ],
    'validation' => [
        'server_required' => 'Select an authoritative server before enabling synchronization.',
        'server_unavailable' => 'The selected server is no longer available or cannot execute compatible Minecraft commands.',
    ],
    'permissions' => [
        'skin' => 'Upload and manage their own Minecraft skin',
        'admin' => 'Manage SkinSystem settings',
    ],
];
